# -*- coding: utf-8 -*-
"""pulse(Sketchbook)_1018_JAR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18DFc8DKRY5U4qh_fIFZmDoq4RXrhn8Cl

### **데이터 불러오기**
"""

import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

filename = '/content/drive/My Drive/pulse_completed_sigs_221018.csv'
df = pd.read_csv(filename)
df.head()

df['default_tf'].value_counts()

"""### **결측값 확인**"""

df['pulse_t_bins'].isnull().sum()

df['pulse_t_bins'].fillna(0.0119, inplace = True)
#df.fillna(0.0119)[['pulse_t_bins']]
df['pulse_t_bins'].isnull().sum()

"""### **중복값 제거**"""

df1 = df.drop_duplicates(subset=['ibk_seq'], keep='last')

df1

"""### **default_tf -> 0,1로 치환**

:74
"""

df1['default_tf'].value_counts()

df1['default_tf'].replace('Y',1,inplace = True)
df1['default_tf'].replace('N',0,inplace = True)

df1['default_tf'].value_counts()

"""### **평균값, 10분위값**"""

for i in range(74,9,-1):
  mean_prob = df1.iloc[:, 6:i].mean(axis = 1)
  df1['mean_tenper{}'.format(i)] = pd.qcut(mean_prob, 10,labels = ['1분위', '2분위', '3분위', '4분위','5분위','6분위','7분위','8분위','9분위','10분위'],precision = 3)
  print(mean_prob, df1['mean_tenper{}'.format(i)])

df1.head()

"""### **부도기업수 측정**"""

for i in range(74,9,-1):
  for j in range(1,11):
    percentile = df1['mean_tenper{}'.format(i)] == '{}분위'.format(j)
    default = df1['default_tf'] == 1

    subset = df1[percentile & default]
    print(i,'까지 나누기', j,'분위', subset['default_tf'].sum())

for i in range(74,9,-1):
  for j in range(1,11):
    oneper_z = df1['mean_tenper{}'.format(i)] == '{}분위'.format(j)
    default_z = df1['default_tf'] == 0

    subset_z = df1[oneper_z & default_z]
    print(i,'까지 나누기', j,'분위', subset_z['default_tf'].value_counts())

#for i in range(75,10,-1):
#  mean_prob = df1.iloc[:, 6:i].mean(axis = 1)
#  df1['mean_tenper'] = pd.qcut(mean_prob, 10, labels = ['1분위', '2분위', '3분위', '4분위','5분위','6분위','7분위','8분위','9분위','10분위'])
#  df1[df1['mean_tenper'] == '1분위']['default_tf']
  #print(mean_prob)
  #print(pd.value_counts(mean_tenper))
  #print(pd.value_counts(mean_tenper))

#for i in range(75,10,-1):
#  mean_prob = df1.iloc[:, 6:i].mean(axis = 1)
#  mean_tenper = pd.qcut(mean_prob, 10)
#  print(i,'까지 평균값 = ', mean_prob)
#  print(i, '까지 평균값의 10분위수 = ', mean_tenper)